[package]
name          = "safe_ffi"
version       = "0.1.0"
authors       = ["MaidSafe Developers <dev@maidsafe.net>"]
description   = "SAFE API - FFI library"
documentation = "http://maidsafe.github.io/safe_ffi/latest/"
repository    = "https://github.com/maidsafe/safe_ffi"
readme        = "README.md"
license       = "GPL-3.0"
homepage      = "http://maidsafe.net"

[lib]
name       = "safe_ffi"
crate_type = ["staticlib", "dylib", "rlib"]

[dependencies]
# ---- Maidsafe ----
routing     = "0.4.*"
safe_nfs    = "0.2.*"
safe_dns    = "0.2.*"
safe_client = "0.2.*"

# ---- Others ----
libc        = "*"
sodiumoxide = "*"

[features]
use-mock-routing = ["safe_dns/use-mock-routing",
                    "safe_nfs/use-mock-routing",
                    "safe_client/use-mock-routing"]
